INSERT INTO Product (PRODUCTID, PRODUCTNAME, UNITPRICE, CATEGORY)
VALUES (1, '테스트상품1', 1000, '완제품');

INSERT INTO Product (PRODUCTID, PRODUCTNAME, UNITPRICE, CATEGORY)
VALUES (2, '테스트상품2', 2500, '완제품');

INSERT INTO Product (PRODUCTID, PRODUCTNAME, UNITPRICE, CATEGORY)
VALUES (3, '원재료A', 500, '원재료');

COMMIT;
